---
repos:
  - repo: git://github.com/Lucas-C/pre-commit-hooks
    rev: v1.1.10
    hooks:
      - id: remove-tabs

  - repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: name-tests-test
      - id: check-added-large-files
      - id: check-byte-order-marker
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-json
      - id: check-symlinks
      - id: detect-private-key
      - id: check-ast
      - id: debug-statements

  - repo: git://github.com/pycqa/pydocstyle.git
    rev: 6.1.1
    hooks:
      - id: pydocstyle
        exclude: _pb2

  - repo: https://github.com/psf/black
    rev: 21.6b0
    hooks:
      - id: black

  - repo: https://github.com/tomcatling/black-nb
    rev: "0.5.0"
    hooks:
      - id: black-nb

  - repo: https://gitlab.com/PyCQA/flake8
    rev: "3.9.2"
    hooks:
      - id: flake8
        additional_dependencies: ["pep8-naming"]
        args:
          ["--ignore", "E2,W5", "--select", "E,W,F,N", "--max-line-length=120"]
        exclude: _pb2
