# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: release_engineering.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor.FileDescriptor(
    name="release_engineering.proto",
    package="ninja.thoth_station.rebuildah",
    syntax="proto3",
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
    serialized_pb=b'\n\x19release_engineering.proto\x12\x1dninja.thoth_station.rebuildah"\x07\n\x05\x45mpty"d\n\x0fSemanticVersion\x12\r\n\x05major\x18\x01 \x01(\x05\x12\r\n\x05minor\x18\x02 \x01(\x05\x12\r\n\x05patch\x18\x03 \x01(\x05\x12\x10\n\x08metadata\x18\x04 \x01(\t\x12\x12\n\nprerelease\x18\x05 \x01(\t",\n\x13\x43ontainerRepository\x12\x15\n\rRepositoryURI\x18\x01 \x01(\t2\xf8\x01\n\x12ReleaseEngineering\x12y\n\x11GetCurrentRelease\x12\x32.ninja.thoth_station.rebuildah.ContainerRepository\x1a..ninja.thoth_station.rebuildah.SemanticVersion"\x00\x12g\n\tPushEvent\x12\x32.ninja.thoth_station.rebuildah.ContainerRepository\x1a$.ninja.thoth_station.rebuildah.Empty"\x00\x62\x06proto3',
)


_EMPTY = _descriptor.Descriptor(
    name="Empty",
    full_name="ninja.thoth_station.rebuildah.Empty",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=60,
    serialized_end=67,
)


_SEMANTICVERSION = _descriptor.Descriptor(
    name="SemanticVersion",
    full_name="ninja.thoth_station.rebuildah.SemanticVersion",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="major",
            full_name="ninja.thoth_station.rebuildah.SemanticVersion.major",
            index=0,
            number=1,
            type=5,
            cpp_type=1,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="minor",
            full_name="ninja.thoth_station.rebuildah.SemanticVersion.minor",
            index=1,
            number=2,
            type=5,
            cpp_type=1,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="patch",
            full_name="ninja.thoth_station.rebuildah.SemanticVersion.patch",
            index=2,
            number=3,
            type=5,
            cpp_type=1,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="metadata",
            full_name="ninja.thoth_station.rebuildah.SemanticVersion.metadata",
            index=3,
            number=4,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="prerelease",
            full_name="ninja.thoth_station.rebuildah.SemanticVersion.prerelease",
            index=4,
            number=5,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=69,
    serialized_end=169,
)


_CONTAINERREPOSITORY = _descriptor.Descriptor(
    name="ContainerRepository",
    full_name="ninja.thoth_station.rebuildah.ContainerRepository",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="RepositoryURI",
            full_name="ninja.thoth_station.rebuildah.ContainerRepository.RepositoryURI",
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=171,
    serialized_end=215,
)

DESCRIPTOR.message_types_by_name["Empty"] = _EMPTY
DESCRIPTOR.message_types_by_name["SemanticVersion"] = _SEMANTICVERSION
DESCRIPTOR.message_types_by_name["ContainerRepository"] = _CONTAINERREPOSITORY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Empty = _reflection.GeneratedProtocolMessageType(
    "Empty",
    (_message.Message,),
    {
        "DESCRIPTOR": _EMPTY,
        "__module__": "release_engineering_pb2"
        # @@protoc_insertion_point(class_scope:ninja.thoth_station.rebuildah.Empty)
    },
)
_sym_db.RegisterMessage(Empty)

SemanticVersion = _reflection.GeneratedProtocolMessageType(
    "SemanticVersion",
    (_message.Message,),
    {
        "DESCRIPTOR": _SEMANTICVERSION,
        "__module__": "release_engineering_pb2"
        # @@protoc_insertion_point(class_scope:ninja.thoth_station.rebuildah.SemanticVersion)
    },
)
_sym_db.RegisterMessage(SemanticVersion)

ContainerRepository = _reflection.GeneratedProtocolMessageType(
    "ContainerRepository",
    (_message.Message,),
    {
        "DESCRIPTOR": _CONTAINERREPOSITORY,
        "__module__": "release_engineering_pb2"
        # @@protoc_insertion_point(class_scope:ninja.thoth_station.rebuildah.ContainerRepository)
    },
)
_sym_db.RegisterMessage(ContainerRepository)


_RELEASEENGINEERING = _descriptor.ServiceDescriptor(
    name="ReleaseEngineering",
    full_name="ninja.thoth_station.rebuildah.ReleaseEngineering",
    file=DESCRIPTOR,
    index=0,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
    serialized_start=218,
    serialized_end=466,
    methods=[
        _descriptor.MethodDescriptor(
            name="GetCurrentRelease",
            full_name="ninja.thoth_station.rebuildah.ReleaseEngineering.GetCurrentRelease",
            index=0,
            containing_service=None,
            input_type=_CONTAINERREPOSITORY,
            output_type=_SEMANTICVERSION,
            serialized_options=None,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.MethodDescriptor(
            name="PushEvent",
            full_name="ninja.thoth_station.rebuildah.ReleaseEngineering.PushEvent",
            index=1,
            containing_service=None,
            input_type=_CONTAINERREPOSITORY,
            output_type=_EMPTY,
            serialized_options=None,
            create_key=_descriptor._internal_create_key,
        ),
    ],
)
_sym_db.RegisterServiceDescriptor(_RELEASEENGINEERING)

DESCRIPTOR.services_by_name["ReleaseEngineering"] = _RELEASEENGINEERING

# @@protoc_insertion_point(module_scope)
